language: python
python: 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37-dj20,py37-dj21,flake8
    - python: 3.6
      env: TOXENV=py36-dj20,py36-dj21,flake8
    - python: 3.5
      env: TOXENV=py35-dj18,py35-dj19,py35-dj110,py35-dj111,py35-dj20,py35-dj21,flake8
    - python: 3.4
      env: TOXENV=py34-dj18,py34-dj19,py34-dj110,py34-dj111,py34-dj20,flake8
    - python: 2.7
      env: TOXENV=py27-dj18,flake8
    - python: pypy
      env: TOXENV=pypy-dj18,pypy-dj19,pypy-dj110,pypy-dj111,flake8
    - python: pypy3
      env: TOXENV=pypy3-dj20,pypy3-dj21,flake8
install:
  - travis_retry pip install tox
script: tox
before_deploy:
  - .tox/py36-dj21/bin/python updatejson.py
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: pmclanahan
  skip_cleanup: true
  password:
    secure: GcjqfBaQPZ7zVv8RsvlihgUaELNp+4X9fdzAF5isjz8MannFIAQHbY25fVrhZSbTNNwxoyzQZEwVhRScBXfAObq2f3FCtYPh6J6u391mqWh8XjbI6QNBUal0hAhRWJpLmt/jKcIDZefON1PHPoJsadEKWOU8b/KsraWlWSG9dCg=
  on:
    tags: true
    repo: mozilla/django-product-details
    python: 3.6
